export default [
	"Adrar",
	"Chlef",
	"Laghouat",
	"Oum El Bouaghi",
	"Batna",
	"Bejaia",
	"Biskra",
	"Bechar",
	"Blida",
	"Bouira",
	"Tamanrasset",
	"Tebessa",
	"Tlemcen",
	"Tiaret",
	"Tizi Ouzou",
	"Algiers",
	"Djelfa",
	"Jijel",
	"Setif",
	"Saida",
	"Skikda",
	"Sidi Bel Abbes",
	"Annaba",
	"Guelma",
	"Constantine",
	"Medea",
	"Mostaganem",
	"Msila",
	"Mascara",
	"Ouargla",
	"Oran",
	"El Bayadh",
	"Illizi",
	"Bordj Bou Arreridj",
	"Boumerdes",
	"El Tarf",
	"Tindouf",
	"Tissemsilt",
	"El Oued",
	"Khenchela",
	"Souk Ahras",
	"Tipaza",
	"Mila",
	"Ain Defla",
	"Naama",
	"Ain Temouchent",
	"Ghardaia",
	"Relizane",
	"El M'Ghair",
	"El Menia",
	"Tamanrasset (Ahaggar)",
	"El Bayadh (El Abiodh Sidi Cheikh)",
	"Illizi (Djanet)",
	"Bordj Bou Arreridj (Medjana)",
	"Boumerdes (Thénia)",
	"El Tarf (Bouhadjar)",
	"Tindouf (Oum El Assel)",
	"Tissemsilt (Lazharia)",
];
